#############################################################################
# Makefile for building: libapplication.so
# Generated by qmake (3.1) (Qt 5.15.0)
# Project:  application.pro
# Template: app
# Command: /data/user/0/com.n0n3m4.droidc/files/gcc/qt/bin/qmake -o Makefile application.pro -spec android-g++
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = aarch64-linux-android-gcc
CXX           = aarch64-linux-android-g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -fstack-protector-strong -DANDROID -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -fstack-protector-strong -DANDROID -O2 -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include -I/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets -I/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui -I/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore -I. -I/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/android-g++
QMAKE         = /data/user/0/com.n0n3m4.droidc/files/gcc/qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /data/user/0/com.n0n3m4.droidc/files/gcc/qt/bin/qmake -install qinstall
QINSTALL_PROGRAM = /data/user/0/com.n0n3m4.droidc/files/gcc/qt/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = libapplication.so1.0.0
DISTDIR = /storage/emulated/0/C4droid_examples/Qt/multifile/application/.tmp/libapplication.so1.0.0
LINK          = aarch64-linux-android-g++
LFLAGS        = -Wl,-soname,libapplication.so -Wl,--no-undefined -Wl,-z,noexecstack -shared
LIBS          = $(SUBLIBS) /data/user/0/com.n0n3m4.droidc/files/gcc/qt/lib/libQt5Widgets.so /data/user/0/com.n0n3m4.droidc/files/gcc/qt/lib/libQt5Gui.so /data/user/0/com.n0n3m4.droidc/files/gcc/qt/lib/libQt5Core.so -lGLESv2   -lstdc++ -llog -lz -lm -ldl -lc -lgcc
AR            = aarch64-linux-android-ar cqs
RANLIB        = aarch64-linux-android-ranlib
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp qrc_application.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qrc_application.o \
		moc_mainwindow.o
DIST          = /data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/spec_pre.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/unix.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/linux.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/sanitize.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/gcc-base.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/gcc-base-unix.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/qdevice.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/device_config.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/android-base-head.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/qconfig.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_androidextras.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_androidextras_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_charts.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_core.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_core_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_gamepad.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_gamepad_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_gui.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_help.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_help_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_location.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_location_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_network.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_network_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_nfc.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_opengl.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_positioning.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qml.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quick.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_repparser.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_scxml.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_sensors.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_serialport.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_sql.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_svg.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_testlib.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_uitools.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_websockets.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_webview.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_widgets.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_xml.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_zlib_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/qt_functions.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/qt_config.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/android-base-tail.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/android-g++/qmake.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/exclusive_builds.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/toolchain.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/default_pre.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/resolve_config.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/default_post.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/android/android.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/android/android_deployment_settings.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/warn_on.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/qt.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/resources_functions.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/resources.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/moc.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/unix/opengl.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/uic.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/unix/thread.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/qmake_use.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/file_copies.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/testcase_targets.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/exceptions.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/yacc.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/lex.prf \
		application.pro mainwindow.h main.cpp \
		mainwindow.cpp
QMAKE_TARGET  = libapplication.so
DESTDIR       = 
TARGET        = libapplication.so


first: all
####### Build rules

libapplication.so:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: application.pro /data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/android-g++/qmake.conf /data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/spec_pre.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/unix.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/linux.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/sanitize.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/gcc-base.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/gcc-base-unix.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/qdevice.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/device_config.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/android-base-head.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/qconfig.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_androidextras.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_androidextras_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_charts.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_charts_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_core.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_core_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_egl_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_gamepad.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_gamepad_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_gui.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_help.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_help_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_input_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_location.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_location_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_network.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_network_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_networkauth.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_networkauth_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_nfc.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_opengl.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_positioning.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qml.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quick.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_remoteobjects.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_repparser.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_repparser_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_scxml.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_scxml_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_sensors.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_serialbus.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_serialport.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_service_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_sql.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_svg.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_testlib.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_texttospeech.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_uitools.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_webchannel.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_websockets.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_webview.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_webview_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_widgets.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_xml.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_zlib_private.pri \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/qt_functions.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/qt_config.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/android-base-tail.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/android-g++/qmake.conf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/exclusive_builds.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/toolchain.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/default_pre.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/resolve_config.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/default_post.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/android/android.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/android/android_deployment_settings.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/warn_on.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/qt.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/resources_functions.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/resources.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/moc.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/unix/opengl.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/uic.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/unix/thread.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/qmake_use.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/file_copies.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/testcase_targets.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/exceptions.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/yacc.prf \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/lex.prf \
		application.pro \
		application.qrc
	$(QMAKE) -o Makefile application.pro -spec android-g++
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/spec_pre.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/unix.conf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/linux.conf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/sanitize.conf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/gcc-base.conf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/gcc-base-unix.conf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/qdevice.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/device_config.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/android-base-head.conf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/qconfig.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_androidextras.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_androidextras_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_bluetooth.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_bluetooth_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_charts.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_charts_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_concurrent.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_core.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_core_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_egl_support_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_gamepad.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_gamepad_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_gui.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_gui_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_help.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_help_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_input_support_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_location.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_location_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_multimedia.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_network.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_network_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_networkauth.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_networkauth_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_nfc.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_nfc_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_opengl.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_positioning.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_printsupport.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qml.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qml_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmltest.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quick.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quick_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_remoteobjects.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_repparser.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_repparser_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_scxml.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_scxml_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_sensors.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_serialbus.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_serialbus_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_serialport.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_serialport_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_service_support_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_sql.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_sql_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_svg.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_svg_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_testlib.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_texttospeech.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_texttospeech_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_uitools.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_webchannel.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_websockets.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_websockets_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_webview.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_webview_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_widgets.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_xml.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_xml_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/modules/qt_lib_zlib_private.pri:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/qt_functions.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/qt_config.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/common/android-base-tail.conf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/android-g++/qmake.conf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/exclusive_builds.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/toolchain.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/default_pre.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/resolve_config.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/default_post.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/android/android.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/android/android_deployment_settings.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/warn_on.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/qt.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/resources_functions.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/resources.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/moc.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/unix/opengl.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/uic.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/unix/thread.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/qmake_use.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/file_copies.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/testcase_targets.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/exceptions.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/yacc.prf:
/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/lex.prf:
application.pro:
application.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile application.pro -spec android-g++

qmake_all: FORCE


all: Makefile libapplication.so

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents application.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_application.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_application.cpp
qrc_application.cpp: application.qrc \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/bin/rcc \
		images/save.png \
		images/open.png \
		images/cut.png \
		images/copy.png \
		images/new.png \
		images/paste.png
	/data/user/0/com.n0n3m4.droidc/files/gcc/qt/bin/rcc -name application application.qrc -o qrc_application.cpp

compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/data/dummy.cpp
	aarch64-linux-android-g++ -fstack-protector-strong -DANDROID -O2 -O2 -Wall -W -dM -E -o moc_predefs.h /data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: mainwindow.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/QMainWindow \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qmainwindow.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtwidgetsglobal.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtguiglobal.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qglobal.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qconfig-bootstrapped.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qconfig.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtcore-config.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsystemdetection.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qprocessordetection.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcompilerdetection.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtypeinfo.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsysinfo.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qlogging.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qflags.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qatomic.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qbasicatomic.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qatomic_bootstrap.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qgenericatomic.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qatomic_cxx11.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qatomic_msvc.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qglobalstatic.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmutex.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qnumeric.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qversiontagging.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtgui-config.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtwidgets-config.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qwidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qwindowdefs.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qobjectdefs.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qnamespace.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qobjectdefs_impl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qwindowdefs_win.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qobject.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstring.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qchar.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qbytearray.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qrefcount.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qarraydata.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringliteral.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringalgorithms.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringview.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringbuilder.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qlist.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qalgorithms.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qiterator.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qhashfunctions.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qpair.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qvector.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcontainertools_impl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qpoint.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qbytearraylist.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringlist.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qregexp.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringmatcher.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcoreevent.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qscopedpointer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmetatype.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qvarlengtharray.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcontainerfwd.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qobject_impl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmargins.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpaintdevice.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qrect.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsize.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpalette.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qcolor.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qrgb.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qrgba64.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qbrush.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qmatrix.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpolygon.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qregion.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qdatastream.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qiodevice.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qline.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtransform.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qimage.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpixelformat.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpixmap.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsharedpointer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qshareddata.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qhash.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsharedpointer_impl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qfont.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qfontmetrics.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qfontinfo.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qsizepolicy.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qcursor.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qkeysequence.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qevent.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qvariant.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmap.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qdebug.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtextstream.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qlocale.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qset.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcontiguouscache.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qurl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qurlquery.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfile.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfiledevice.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qvector2d.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtouchdevice.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtabwidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qicon.h \
		moc_predefs.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/bin/moc
	/data/user/0/com.n0n3m4.droidc/files/gcc/qt/bin/moc $(DEFINES) --include /storage/emulated/0/C4droid_examples/Qt/multifile/application/moc_predefs.h -I/data/user/0/com.n0n3m4.droidc/files/gcc/qt/mkspecs/android-g++ -I/storage/emulated/0/C4droid_examples/Qt/multifile/application -I/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include -I/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets -I/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui -I/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore -I/data/user/0/com.n0n3m4.droidc/files/gcc/aarch64-linux-android/include/c++/10.2.0 -I/data/user/0/com.n0n3m4.droidc/files/gcc/lib/gcc/aarch64-linux-android/10.2.0/include -I/data/user/0/com.n0n3m4.droidc/files/gcc/lib/gcc/aarch64-linux-android/10.2.0/include-fixed -I/data/user/0/com.n0n3m4.droidc/files/gcc/aarch64-linux-android/include mainwindow.h -o moc_mainwindow.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/QApplication \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qapplication.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtwidgetsglobal.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtguiglobal.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qglobal.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qconfig-bootstrapped.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qconfig.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtcore-config.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsystemdetection.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qprocessordetection.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcompilerdetection.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtypeinfo.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsysinfo.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qlogging.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qflags.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qatomic.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qbasicatomic.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qatomic_bootstrap.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qgenericatomic.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qatomic_cxx11.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qatomic_msvc.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qglobalstatic.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmutex.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qnumeric.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qversiontagging.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtgui-config.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtwidgets-config.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcoreapplication.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstring.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qchar.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qbytearray.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qrefcount.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qnamespace.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qarraydata.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringliteral.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringalgorithms.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringview.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringbuilder.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qobject.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qobjectdefs.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qobjectdefs_impl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qlist.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qalgorithms.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qiterator.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qhashfunctions.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qpair.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qvector.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcontainertools_impl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qpoint.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qbytearraylist.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringlist.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qregexp.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringmatcher.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcoreevent.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qscopedpointer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmetatype.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qvarlengtharray.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcontainerfwd.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qobject_impl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qeventloop.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qwindowdefs.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qwindowdefs_win.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsize.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmargins.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qcursor.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qdesktopwidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qwidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpaintdevice.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qrect.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpalette.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qcolor.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qrgb.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qrgba64.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qbrush.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qmatrix.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpolygon.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qregion.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qdatastream.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qiodevice.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qline.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtransform.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qimage.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpixelformat.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpixmap.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsharedpointer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qshareddata.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qhash.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsharedpointer_impl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qfont.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qfontmetrics.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qfontinfo.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qsizepolicy.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qkeysequence.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qevent.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qvariant.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmap.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qdebug.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtextstream.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qlocale.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qset.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcontiguouscache.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qurl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qurlquery.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfile.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfiledevice.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qvector2d.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtouchdevice.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qguiapplication.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qinputmethod.h \
		mainwindow.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/QMainWindow \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qmainwindow.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtabwidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qicon.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp /data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/QtWidgets \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/QtWidgetsDepends \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QtCore \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QtCoreDepends \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qglobal.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qconfig-bootstrapped.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qconfig.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtcore-config.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsystemdetection.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qprocessordetection.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcompilerdetection.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtypeinfo.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsysinfo.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qlogging.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qflags.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qatomic.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qbasicatomic.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qatomic_bootstrap.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qgenericatomic.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qatomic_cxx11.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qatomic_msvc.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qglobalstatic.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmutex.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qnumeric.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qversiontagging.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qabstractanimation.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qobject.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qobjectdefs.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qnamespace.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qobjectdefs_impl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstring.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qchar.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qbytearray.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qrefcount.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qarraydata.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringliteral.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringalgorithms.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringview.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringbuilder.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qlist.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qalgorithms.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qiterator.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qhashfunctions.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qpair.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qvector.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcontainertools_impl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qpoint.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qbytearraylist.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringlist.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qregexp.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringmatcher.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcoreevent.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qscopedpointer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmetatype.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qvarlengtharray.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcontainerfwd.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qobject_impl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qabstracteventdispatcher.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qeventloop.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qabstractitemmodel.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qvariant.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmap.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qdebug.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qhash.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtextstream.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qiodevice.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qlocale.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qshareddata.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qset.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcontiguouscache.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsharedpointer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsharedpointer_impl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qabstractnativeeventfilter.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qabstractproxymodel.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qabstractstate.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qabstracttransition.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qanimationgroup.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qarraydataops.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qarraydatapointer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qbasictimer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qbitarray.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qbuffer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qbytearraymatcher.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcache.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcalendar.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcborarray.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcborvalue.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qdatetime.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcborcommon.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qregularexpression.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qurl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qurlquery.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/quuid.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcbormap.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcborstream.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcborstreamreader.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfloat16.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcborstreamwriter.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcollator.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcommandlineoption.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcommandlineparser.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcoreapplication.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qconcatenatetablesproxymodel.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qcryptographichash.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qdatastream.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qdeadlinetimer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qelapsedtimer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qdir.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfileinfo.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfile.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfiledevice.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qdiriterator.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qeasingcurve.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qendian.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qeventtransition.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qexception.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfactoryinterface.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfileselector.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QObject \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QStringList \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfilesystemwatcher.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfinalstate.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfuture.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfutureinterface.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qrunnable.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qresultstore.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfuturesynchronizer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qfuturewatcher.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qhistorystate.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qidentityproxymodel.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qisenum.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qitemselectionmodel.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qjsonarray.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qjsonvalue.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qjsondocument.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qjsonobject.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qlibrary.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qlibraryinfo.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qversionnumber.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qline.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qlinkedlist.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qlockfile.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qloggingcategory.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmargins.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmath.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmessageauthenticationcode.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmetaobject.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmimedata.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmimedatabase.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qmimetype.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qobjectcleanuphandler.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qoperatingsystemversion.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qparallelanimationgroup.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qpauseanimation.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qplugin.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qpointer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qpluginloader.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qprocess.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qpropertyanimation.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qvariantanimation.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qqueue.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qrandom.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qreadwritelock.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qrect.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsize.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qresource.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsavefile.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qscopedvaluerollback.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qscopeguard.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsemaphore.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsequentialanimationgroup.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsettings.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsharedmemory.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsignalmapper.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsignaltransition.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsocketnotifier.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsortfilterproxymodel.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstack.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstandardpaths.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstate.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstatemachine.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstorageinfo.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qstringlistmodel.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qsystemsemaphore.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtemporarydir.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtemporaryfile.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtextboundaryfinder.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtextcodec.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qthread.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qthreadpool.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qthreadstorage.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtimeline.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtimer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtimezone.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtranslator.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtransposeproxymodel.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtypetraits.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qwaitcondition.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QDeadlineTimer \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qwineventnotifier.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qxmlstream.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qtcoreversion.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/QtGui \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/QtGuiDepends \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtguiglobal.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtgui-config.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qabstracttextdocumentlayout.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtextlayout.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qcolor.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qrgb.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qrgba64.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qevent.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qwindowdefs.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qwindowdefs_win.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qregion.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qkeysequence.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qvector2d.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtouchdevice.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtextformat.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qfont.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpen.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qbrush.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qmatrix.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpolygon.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtransform.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qimage.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpaintdevice.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpixelformat.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpixmap.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtextoption.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qglyphrun.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qrawfont.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qfontdatabase.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtextcursor.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtextdocument.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpalette.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qaccessible.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qaccessiblebridge.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qaccessibleobject.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qaccessibleplugin.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qbackingstore.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qwindow.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QEvent \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QMargins \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QRect \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qsurface.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qsurfaceformat.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qicon.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qcursor.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qbitmap.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qclipboard.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qcolorspace.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qcolortransform.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qdesktopservices.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qdrag.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qfontinfo.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qfontmetrics.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qgenericmatrix.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qgenericplugin.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qgenericpluginfactory.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qguiapplication.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qinputmethod.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qiconengine.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qiconengineplugin.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qimageiohandler.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qimagereader.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qimagewriter.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qmatrix4x4.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qvector3d.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qvector4d.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qquaternion.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qmovie.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qoffscreensurface.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopengl.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/qt_windows.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopengles2ext.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopenglext.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopenglbuffer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopenglcontext.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QScopedPointer \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/QSurfaceFormat \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopenglversionfunctions.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopengldebug.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopenglextrafunctions.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopenglfunctions.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopenglframebufferobject.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopenglpaintdevice.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopenglpixeltransferoptions.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QSharedDataPointer \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopenglshaderprogram.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopengltexture.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopengltextureblitter.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/QMatrix3x3 \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/QMatrix4x4 \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopengltimerquery.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopenglvertexarrayobject.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qopenglwindow.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/QPaintDeviceWindow \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpaintdevicewindow.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/QWindow \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/QPaintDevice \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/QOpenGLContext \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/QImage \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpagedpaintdevice.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpagelayout.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpagesize.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpaintengine.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpainter.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpainterpath.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpdfwriter.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpicture.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpictureformatplugin.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qpixmapcache.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qrasterwindow.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qscreen.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QList \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QSize \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QSizeF \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/QTransform \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qsessionmanager.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qstandarditemmodel.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qstatictext.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qstylehints.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qsyntaxhighlighter.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtextobject.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtextdocumentfragment.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtextdocumentwriter.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtextlist.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtexttable.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qvalidator.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/qtguiversion.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtwidgetsglobal.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtwidgets-config.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qabstractbutton.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qwidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qsizepolicy.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qabstractitemdelegate.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qstyleoption.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qabstractspinbox.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qslider.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qabstractslider.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qstyle.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtabbar.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtabwidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qrubberband.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qframe.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qabstractitemview.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qabstractscrollarea.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qaccessiblewidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qaction.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qactiongroup.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qapplication.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qdesktopwidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qboxlayout.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qlayout.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qlayoutitem.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgridlayout.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qbuttongroup.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qcalendarwidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qcheckbox.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qcolordialog.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qdialog.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qcolormap.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qcolumnview.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qcombobox.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qcommandlinkbutton.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qpushbutton.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qcommonstyle.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qcompleter.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qdatawidgetmapper.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qdatetimeedit.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qdial.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qdialogbuttonbox.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qdirmodel.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qfileiconprovider.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qdockwidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qdrawutil.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qerrormessage.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qfiledialog.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qfilesystemmodel.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qfocusframe.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qfontcombobox.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qfontdialog.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qformlayout.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/QLayout \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgesture.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgesturerecognizer.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgraphicsanchorlayout.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgraphicsitem.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgraphicslayout.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgraphicslayoutitem.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgraphicseffect.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgraphicsgridlayout.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgraphicsitemanimation.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgraphicslinearlayout.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgraphicsproxywidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgraphicswidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgraphicsscene.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgraphicssceneevent.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgraphicstransform.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtGui/QVector3D \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgraphicsview.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qscrollarea.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qgroupbox.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qheaderview.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qinputdialog.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qlineedit.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qitemdelegate.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qitemeditorfactory.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qkeyeventtransition.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qkeysequenceedit.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qlabel.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qlcdnumber.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qlistview.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qlistwidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qmainwindow.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qmdiarea.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qmdisubwindow.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qmenu.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qmenubar.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qmessagebox.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qmouseeventtransition.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qopenglwidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/QWidget \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qplaintextedit.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtextedit.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qprogressbar.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qprogressdialog.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qproxystyle.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/QCommonStyle \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qradiobutton.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qscrollbar.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qscroller.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QPointF \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/QScrollerProperties \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qscrollerproperties.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QMetaType \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtCore/QVariant \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qshortcut.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qsizegrip.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qspinbox.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qsplashscreen.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qsplitter.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qstackedlayout.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qstackedwidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qstatusbar.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qstyleditemdelegate.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qstylefactory.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qstylepainter.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qstyleplugin.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qsystemtrayicon.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtableview.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtablewidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtextbrowser.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtoolbar.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtoolbox.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtoolbutton.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtooltip.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtreeview.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtreewidget.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtreewidgetitemiterator.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qundogroup.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qundostack.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qundoview.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qwhatsthis.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qwidgetaction.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qwizard.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/qtwidgetsversion.h \
		mainwindow.h \
		/data/user/0/com.n0n3m4.droidc/files/gcc/qt/include/QtWidgets/QMainWindow
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_application.o qrc_application.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/libs/arm64-v8a/ || mkdir -p $(INSTALL_ROOT)/libs/arm64-v8a/
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/libs/arm64-v8a/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/libs/arm64-v8a/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/libs/arm64-v8a/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

